[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # Handle 404s after client-side routing fails
  from = "/*"
  to = "/404"
  status = 404
  force = false

[build]
  publish = "dist"
  command = "pnpm run build"
  # Add ignore command to check commit messages
  ignore = "git log -1 --pretty=%B | grep -E '\\[skip ci\\]|\\[skip netlify\\]'"

# Add custom headers for performance optimization
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=31536000"

# Specific caching for static assets
[[headers]]
  for = "/*.{js,css,png,jpg,jpeg,webp,svg,gif}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add specific headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Robots-Tag = "index, follow"